train_file: '/mnt/datasets/ego4d-256/egoimgtext/train_P9Dformat.json'
test_file: '/mnt/datasets/ego4d-256/egoimgtext/test_3k_P9Dformat.json'
query_file: '/mnt/datasets/ego4d-256/egoimgtext/test_1k_P9Dformat.json'
gallery_file: '/mnt/datasets/ego4d-256/egoimgtext/test_1k_P9Dformat.json'
train_image_root: '/mnt/datasets/ego4d-256/egoimgtext/imgs'
test_image_root: '/mnt/datasets/ego4d-256/egoimgtext/imgs'
gallery_image_root: '/mnt/datasets/ego4d-256/egoimgtext/imgs'

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
image_size: 224
batch_size_train: 64
batch_size_test: 512

# optimizer
weight_decay: 0.05
init_lr: 1e-4
min_lr: 1e-6
k_test: 10
max_words: 30
window_size: 50

#CL
max_epoch: 5
task: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
base_mode: 'seqF'
mode: 'seq'

