train_file: '/mnt/datasets/P9D/json/train.json'
test_file: '/mnt/datasets/P9D/json/test.json'
query_file: '/mnt/datasets/P9D/json/query.json'
gallery_file: '/mnt/datasets/P9D/json/gallery.json'
train_image_root: '/mnt/datasets/P9D/train_images'
test_image_root: '/mnt/datasets/P9D/gallery_images'
gallery_image_root: '/mnt/datasets/P9D/gallery_images'

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
image_size: 224
batch_size_train: 64
batch_size_test: 512

# optimizer
weight_decay: 0.05
init_lr: 1e-5
min_lr: 1e-6
k_test: 10
max_words: 30
window_size: 50

#CL
max_epoch: 5
task: ['家居用品', '家装家饰', '食品/保健', '美容护理',  '服饰鞋包', '车品配件', '母婴','运动/户外', '3C数码']
base_mode: 'seqF'
mode: 'seq'

